import = ["/home/nan/.config/alacritty/themes/gruvbox_dark.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Fira Code Nerd Font Mono"
style = "Regular"

[shell]
args = ["--login"]
program = "/usr/bin/bash"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 3
y = 3
